# Generated by Django 5.2.6 on 2025-09-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
